import React from "react";
import { useLocation, useNavigate } from "react-router-dom";
import Card from "./Card";

const subjects = {
  IT: {
    "SEM I": ["SPC", "Maths", "ECS", "Chemistry", "Engg. Graphics"],
    "SEM II": ["Maths-II", "Java", "BEE", "CEM", "Physics", "FIT"],
    "SEM III": [
      "Data Structures",
      "Database Management System",
      "Web Programming Laboratory",
      "Operating System",
      "Design Thinking Laboratory",
      "Universal Human Values",
      "Community Engagement Service",
      "Innovative Product Development I (Audit)",
      "Open Elective I",
    ],
    "SEM IV": [
      "Applied Mathematics",
      "Design and Analysis of Algorithms",
      "Python Programming Laboratory",
      "Object-Oriented Design Laboratory",
      "Formal Languages and Automata Theory",
      "Professional and Business Communication Tutorial",
      "Economics and Financial Management",
      "Innovative Product Development II (Audit)",
      "Open Elective II",
    ],
    "SEM V": [
      "Computer Networks",
      "Artificial Intelligence",
      "Data Warehousing and Mining",
      "Statistical Analysis",
      "Advanced Data Structures and Algorithms (Dept. Elective)",
      "Microcontrollers and Embedded Systems (Dept. Elective)",
      "Computer Graphics (Dept. Elective)",
      "User Centered Design (Dept. Elective)",
      "Constitution of India",
      "Innovative Product Development III (Credit)",
    ],
    "SEM VI": [
      "Software Engineering",
      "Cryptography and Network Security",
      "Machine Learning",
      "Image Processing and Computer Vision (Dept. Elective)",
      "Infrastructure Security (Dept. Elective)",
      "Internet of Things (Dept. Elective)",
      "Game Design (Dept. Elective)",
      "Big Data Analysis (Dept. Elective)",
      "Enterprise Governance of Information Technology (Dept. Elective)",
      "Cloud Computing (Dept. Elective)",
      "Innovative Product Development IV (Credit)",
    ],
    "SEM VII": [
      "Service Oriented Architecture",
      "Parallel and Distributed Computing",
      "Blockchain Technology (Dept. Elective)",
      "User Centered Design (Dept. Elective)",
      "Wireless Sensor Network (Dept. Elective)",
      "Deep Learning (Dept. Elective)",
      "Business Analytics (Dept. Elective)",
      "Institute Level Optional Courses- I",
      "Project Stage- I",
    ],
    "SEM VIII": [
      "Semantic Web Technology",
      "Design Patterns",
      "Industrial Internet of Things (Dept. Elective)",
      "Gamification (Dept. Elective)",
      "Predictive Analytics (Dept. Elective)",
      "Advanced Machine Learning (Dept. Elective)",
      "Advanced Security (Dept. Elective)",
      "Institute Level Optional Courses- II",
      "Project Stage- II",
    ],
  },

  Comps: {
    "SEM I": ["SPC", "Maths", "ECS", "Chemistry", "Engg. Graphics"],
    "SEM II": ["Maths-II", "Java", "BEE", "CEM", "Physics", "FCT"],
    "SEM III": [
      "Engineering Mathematics-III",
      "Data Structures",
      "Discrete Structures",
      "Database Management Systems",
      "Digital Electronics",
      "Programming Laboratory-I (Java)",
      "Innovative Product Development-I (Audit)",
      "Constitution of India (Audit)",
    ],
    "SEM IV": [
      "Engineering Mathematics-IV",
      "Formal Language & Automata Theory",
      "Operating System",
      "Analysis of Algorithms",
      "Computer Networks",
      "Universal Human Values",
      "Innovative Product Development-II (Audit)",
    ],
    "SEM V": [
      "Data Mining and Warehouse",
      "Processor Organization and Architecture",
      "Artificial Intelligence",
      "Professional and Business Communication Laboratory",
      "Advanced Operating System (Dept. Elective)",
      "Advanced Database Management System (Dept. Elective)",
      "Network Engineering (Dept. Elective)",
      "Programming Laboratory-II (Python)",
      "Innovative Product Development-III (Credit)",
    ],
    "SEM VI": [
      "Software Engineering",
      "Advance Algorithm",
      "Information Security",
      "Big Data Infrastructure (Dept. Elective)",
      "Internet of Things (Dept. Elective)",
      "Business Analytics (Dept. Elective)",
      "Machine Learning (Dept. Elective)",
      "Compiler Design (Dept. Elective)",
      "Human Machine Interaction (Dept. Elective)",
      "Innovative Product Development-IV (Credit)",
      "Environmental Studies (Audit)",
    ],
    "SEM VII": [
      "Digital Signal Processing and Applications",
      "Distributed Computing",
      "Deep Learning (Dept. Elective)",
      "BlockChain Technology (Dept. Elective)",
      "Predictive Modeling (Dept. Elective)",
      "Institute Level Optional Courses- I",
      "Project Stage- I",
    ],
    "SEM VIII": [
      "Web Intelligence",
      "High Performance Computing",
      "Natural Language Processing (Dept. Elective)",
      "Software Architecture (Dept. Elective)",
      "Software Testing and Quality Assurance (Dept. Elective)",
      "Institute Level Optional Courses- II",
      "Project Stage- II",
    ],
  },

  "CSE-DS": {
    "SEM I": ["SPC", "Maths", "ECS", "Chemistry", "Engg. Graphics"],
    "SEM II": ["Maths-II", "Java", "BEE", "CEM", "Physics", "FDA"],
    "SEM III": [
      "Computer System Fundamentals",
      "Database Systems",
      "Data Science Laboratory (Python)",
      "Mathematics for Intelligent Systems",
      "Design Thinking Laboratory",
      "Innovative Product Development I",
      "Universal Human Values",
      "Open Elective I",
      "Financial Market and Risk Analysis (Honors)",
    ],
    "SEM IV": [
      "Data Structures",
      "Machine Learning - I",
      "Statistics for Data Science",
      "Web Engineering Laboratory",
      "Innovative Product Development II",
      "Economics and Financial Management",
      "Professional and Business Communication",
      "Open Elective II",
      "Computational Methods and Pricing Models (Honors)",
    ],
    "SEM V": [
      "Machine Learning-II (Deep Learning)",
      "Design and Analysis of Algorithms",
      "Intelligent Systems",
      "Cloud Computing and Security (Dept. Elective)",
      "Computer Communication and Networks (Multidisciplinary Course)",
      "DevOps Laboratory (Open Elective)",
      "Advanced Java Laboratory (Open Elective)",
      "Innovative Product Development III",
      "Econometric Modelling (Honors)",
    ],
    "SEM VI": [
      "Machine Learning - III (Reinforcement Learning)",
      "Natural Language Text Processing",
      "Data Engineering",
      "Time Series Analysis",
      "Computational Neuroscience (Dept. Elective)",
      "Image Processing and Computer Vision",
      "Robotics",
      "Innovative Product Development IV",
      "Quantitative Portfolio Management (Honors)",
    ],
    "SEM VII": [
      "Language Models",
      "High Performance Computing",
      "Data Ethics",
      "Geo-Spatial Data Science (Dept. Elective)",
      "Quantum Computing",
      "Advanced Machine Learning (Minor)",
      "Computational Motion Planning",
      "Project Stage - I",
      "Financial Decision Making (Honors)",
    ],
    "SEM VIII": [
      "Internship/ On Job Training (OJT)",
      "Open Digital Library Courses/MOOC",
      "Project Stage - II",
    ],
  },

  AIDS: {
    "SEM I": ["SPC", "Maths", "BEE", "CEM", "Physics"],
    "SEM II": [
      "Maths-II",
      "Java",
      "ECS",
      "Chemistry",
      "Engg. Graphics",
      "FAIDS",
    ],
    "SEM III": [
      "Engineering Mathematics-III",
      "Data Structures and Algorithms",
      "Database Management System",
      "Operating Systems",
      "Programming Laboratory-I (Python Programming)",
      "Constitution of India",
      "Innovative Product Development I (A)",
    ],
    "SEM IV": [
      "Statistics for Engineers",
      "Artificial Intelligence",
      "Foundation of Data Science",
      "Computer Networks & Security",
      "Programming Laboratory II (Web Development)",
      "Universal Human Values",
      "Innovative Product Development II (B)",
    ],
    "SEM V": [
      "Machine Learning",
      "Advanced Algorithms",
      "Cloud Computing",
      "Data Engineering & Visualization Laboratory",
      "Department Elective 1- DevOps",
      "Department Elective 2- Spatial Data Analytics",
      "Department Elective 3- Computer Graphics & Virtual Reality",
      "Department Elective 4- Web Programming",
      "Environmental Studies",
      "Innovative Product Development III (C)",
    ],
    "SEM VI": [
      "Computer Vision-I",
      "Time Series Analysis",
      "Natural Language Processing",
      "Open Source Technologies Laboratory",
      "Department Elective 1- MLOps",
      "Department Elective 2- Game Programming",
      "Department Elective 3- Computational Intelligence",
      "Department Elective 4- Text, Web & Social Analytics",
      "Professional Communication & Ethics",
      "Innovative Product Development IV (D)",
    ],
    "SEM VII": [
      "Computer Vision-II",
      "High Performance Computing",
      "UI/UX Design",
      "Robotics & AI",
      "IoT & Edge Computing",
      "Probabilistic Models",
      "Institute Elective",
      "Project - I",
    ],
    "SEM VIII": [
      "Reinforcement Learning",
      "Secure Software Systems",
      "Adv. Business Intelligence",
      "Quantum AI",
      "Block Chain Architecture",
      "Web Intelligence",
      "Institute Elective",
      "Project - II",
    ],
  },

  Mech: {
    "SEM I": ["SPC", "Maths", "BEE", "CEM", "Physics"],
    "SEM II": ["Maths-II", "Java", "ECS", "Chemistry", "Engg. Graphics", "EME"],
    "SEM III": [
      "Engineering Mathematics III",
      "Engineering Thermodynamics",
      "Strength of Materials",
      "Manufacturing Processes",
      "Materials Technology",
      "Computer Aided Machine Drawing Laboratory",
      "Machine Shop Practice I",
      "Innovative Product Development I",
      "Constitution of India (Audit Course)",
    ],
    "SEM IV": [
      "Engineering Mathematics IV",
      "Fluid Mechanics",
      "Mechanical Measurements and Metrology",
      "Advanced Manufacturing Processes",
      "Kinematics of Machinery",
      "Machine Shop Practice II",
      "Universal Human Values",
      "Innovative Product Development II",
    ],
    "SEM V": [
      "Automotive Prime Movers",
      "Heat Transfer",
      "Mechanical Vibrations",
      "Industrial Electronics and Controls",
      "Machine Tool Engineering (Dept. Elective)",
      "Renewable Energy Systems (Dept. Elective)",
      "Quality Engineering (Dept. Elective)",
      "Python for Mechanical Engineering",
      "Professional and Business Communication Laboratory",
      "Innovative Product Development - III",
    ],
    "SEM VI": [
      "Machine Design I",
      "Refrigeration and Air Conditioning",
      "Mechatronics",
      "Power Engineering",
      "Smart Materials (Dept. Elective)",
      "Design of Heat Exchanger Equipments (Dept. Elective)",
      "Reliability Engineering (Dept. Elective)",
      "Database Management Systems",
      "Innovative Product Development - IV",
      "Environmental Studies (Audit Course)",
    ],
    "SEM VII": [
      "Machine Design II",
      "Production Planning and Control",
      "Finite Element Analysis",
      "Additive Manufacturing (Dept. Elective)",
      "Computational Fluid Dynamics (Dept. Elective)",
      "Machine Health Monitoring Management (Dept. Elective)",
      "Big Data Analysis (Dept. Elective)",
      "Robotics (Dept. Elective)",
      "Tribology (Dept. Elective)",
      "Automobile Engineering (Dept. Elective)",
      "Institute Level Optional Courses- I",
      "Project Stage- I",
    ],
    "SEM VIII": [
      "Design of Mechanical Systems",
      "Industrial Engineering",
      "CAD/CAM/CIM",
      "Smart Industries (Dept. Elective)",
      "Sustainable Energy Management (Dept. Elective)",
      "Industrial Waste Management (Dept. Elective)",
      "Business Analytics (Dept. Elective)",
      "IoT and Applications (Dept. Elective)",
      "Process Equipment Design (Dept. Elective)",
      "Motor Sports Engineering (Dept. Elective)",
      "Advanced Quantitative Techniques (Dept. Elective)",
      "Institute Level Optional Courses- II",
      "Project Stage- II",
    ],
  },

  AIML: {
    "SEM I": ["SPC", "Maths", "BEE", "CEM", "Physics"],
    "SEM II": [
      "Maths-II",
      "Java",
      "ECS",
      "Chemistry",
      "Engg. Graphics",
      "FAIML",
    ],
    "SEM III": [
      "Linear Algebra and Optimization Techniques",
      "Data Structures",
      "Python Laboratory",
      "Operating Systems",
      "Product Lifecycle Management",
      "Management Information System",
      "Operations Research",
      "Personal Finance Management",
      "Public System & Policies",
      "Fundamentals of Biomedical Instruments",
      "IPR & Patenting",
      "Entrepreneurship and Startup Ecosystem",
      "Professional and Business Communication",
      "Economics and Financial Management",
      "Community Engagement Service",
      "Innovative Product Development I",
    ],
    "SEM IV": [
      "Probability and Statistical Inference",
      "Design and Analysis of Algorithms",
      "Artificial Intelligence",
      "Programming Laboratory-II (Web Development)",
      "Project Management",
      "Cyber Security, Policies and Laws",
      "Advanced Operations Research",
      "Corporate Finance Management",
      "Corporate Social Responsibility",
      "Bioinformatics",
      "Human Resource Management",
      "Digital Marketing Management",
      "Logistics and Supply Chain Management",
      "Database Management Systems",
      "Design Thinking",
      "Universal Human Values",
      "Innovative Product Development II",
    ],
    "SEM V": [
      "Machine Learning",
      "Natural Language Processing",
      "Image Processing and Computer Vision",
      "Computer Network",
      "Programming Laboratory-III (Full Stack Development using NextJs)",
      "Human Machine Interaction",
      "Advanced Data Structures and Algorithms",
      "Recommendation Systems",
      "Environmental Studies",
      "Innovative Product Development III",
    ],
    "SEM VI": [
      "Large Language Models",
      "Deep Learning",
      "MLOPS & DEVOPS",
      "Internet of Things",
      "Probabilistic Graph Models",
      "Cybersecurity",
      "AI in Healthcare",
      "Time Series Analysis for Financial Applications",
      "Robotics",
      "Big Data Analytics",
    ],
    "SEM VII": [
      "High Performance Computing",
      "Large Language Models",
      "Big Data Laboratory",
      "Robotics",
      "Artificial Intelligence in Finance",
      "Artificial Intelligence in Cybersecurity",
      "Product Lifecycle Management",
      "Management Information System",
      "Operations Research",
      "Cyber Security and Laws",
      "Personal Finance Management",
      "Energy Audit and Management",
      "Disaster Management and Mitigation Measures",
      "Science of Well-being",
      "Research Methodology",
      "Public Systems and Policies",
      "Project Stage I",
    ],
    "SEM VIII": [
      "Reinforcement Learning",
      "Ethical AI",
      "AI in Healthcare",
      "Quantum AI",
      "Image Generative AI",
      "Project Management",
      "Entrepreneurship Development and Management",
      "Corporate Social Responsibility",
      "Human Resource Management",
      "Corporate Finance Management",
      "Logistics and Supply Chain Management",
      "IPR and Patenting",
      "Digital Marketing Management",
      "Environmental Management",
      "Labour and Corporate Law",
      "Project Stage II",
    ],
  },

  EXTC: {
    "SEM I": ["SPC", "Maths", "BEE", "CEM", "Physics"],
    "SEM II": ["Maths-II", "Java", "ECS", "Chemistry", "Engg. Graphics", "EN"],
    "SEM III": [
      "Engineering Mathematics - III",
      "Electronics Circuit Design",
      "Digital System Design",
      "Signals & Systems",
      "Electrical Networks Analysis & Synthesis Laboratory",
      "Python Programming Laboratory",
      "Universal Human Values",
      "Innovative Product Development-I",
    ],
    "SEM IV": [
      "Engineering Mathematics - IV",
      "Integrated Circuits",
      "Electromagnetic Wave Propagation",
      "Microcontroller & Applications-I",
      "Data Analytics Laboratory",
      "Database Management System Laboratory",
      "Constitution of India",
      "Innovative Product Development-II",
    ],
    "SEM V": [
      "Analog Communication",
      "Radio Frequency Circuit Design",
      "Microcontroller & Applications II",
      "Digital Signal Processing",
      "Data Structures & Algorithms",
      "Environmental Engineering",
      "Innovative Product Development III",
    ],
    "SEM VI": [
      "Digital Communication",
      "Radiating Systems",
      "Computer Networks",
      "Fundamentals of Digital Image Processing",
      "Basic VLSI",
      "Control Systems",
      "Neural Network & Fuzzy Logic",
      "Operating Systems",
      "Big Data Analytics",
      "Radar Engineering",
      "Linear Algebra",
      "Professional & Business Communication Laboratory",
      "Innovative Product Development IV",
    ],
    "SEM VII": [
      "Microwave Engineering",
      "Mobile Communication System",
      "Internet of Things",
      "Artificial Intelligence & Machine Learning",
      "Robotics",
      "Power Electronics",
      "Data Compression & Encryption",
      "Speech Processing",
      "Embedded Systems",
      "Advanced VLSI",
      "Institute Professional Elective",
      "Industrial Automation Laboratory",
      "Project Stage - I",
    ],
    "SEM VIII": [
      "Optical Communication",
      "Wireless Network",
      "5G Technology",
      "Computer Vision",
      "Satellite Communication",
      "Internet Engineering & Network Security",
      "Machine Learning for Signal Processing",
      "Advanced Digital Signal Processing",
      "Microwave Amplifier & Oscillator Design",
      "Institute Professional Elective",
      "Project Stage - II",
    ],
  },

  ICB: {
    "SEM I": ["SPC", "Maths", "BEE", "CEM", "Physics"],
    "SEM II": [
      "Maths-II",
      "Java",
      "ECS",
      "Chemistry",
      "Engg. Graphics",
      "FSST",
    ],
    "SEM III": [
      "Linear Algebra and Optimization Techniques",
      "Data Structures",
      "Database Management Systems",
      "Operating Systems",
      "Professional and Business Communication Tutorial",
      "Economics and Financial Management",
      "Community Engagement Service",
      "Innovative Product Development I",
    ],
    "SEM IV": [
      "Statistics for Engineers",
      "Design and Analysis of Algorithms",
      "Computer Networks",
      "Python Programming Laboratory",
      "Theoretical Computer Science",
      "Project Management",
      "Cyber Security, Policies and Laws",
      "Advanced Operations Research",
      "Corporate Finance Management",
      "Corporate Social Responsibility",
      "Bioinformatics",
      "Human Resource Management",
      "Digital Marketing Management",
      "Logistics and Supply Chain Management",
      "Innovative Product Development II",
      "Design Thinking Laboratory",
      "Universal Human Values",
    ],
    "SEM V": [
      "Embedded System and IoT",
      "Applied Cryptography",
      "Introduction to Blockchain Technology",
      "Web Application Development Laboratory",
      "Distributed Computing (Department Elective)",
      "Computer Vision (Department Elective)",
      "Cognitive Computing (Department Elective)",
      "Artificial Intelligence",
      "Environmental Studies",
      "Innovative Product Development II",
    ],
    "SEM VI": [
      "Secure Software Engineering",
      "Data Engineering",
      "Big Data Analytics",
      "Machine Learning (Department Elective)",
      "Mobile Device Security and Forensics (Department Elective)",
      "Cryptocurrency Technology (Department Elective)",
      "Cloud Computing Laboratory",
      "Professional and Business Communication",
      "Innovative Product Development IV",
    ],
    "SEM VII": [
      "Blockchain for Cybersecurity",
      "Industrial Internet of Everything",
      "Deep Learning",
      "Malware Analysis (Department Level Elective)",
      "Software Testing and Quality Assurance (Department Level Elective)",
      "Project Stage I",
    ],
    "SEM VIII": [
      "Social Network Analysis",
      "Ethical Hacking and Digital Forensics",
      "Computer Vision (Department Level Elective)",
      "Industrial Internet of Everything (Department Level Elective)",
      "Software Testing and Quality Assurance (Department Level Elective)",
      "Project Stage II",
    ],
  },
};

const Subjects = () => {
  const navigate = useNavigate();
  const { state } = useLocation();
  const { branch, sem, examType } = state;
  const subjectList = subjects[branch][sem];
  return (
    <div className="bg-[#dbc397] min-h-screen flex flex-col items-center p-6 gap-6">
      <p className="font-bold text-4xl text-amber-900">
        {sem} — {branch}
      </p>

      {subjectList.length > 0 ? (
        <div className="grid grid-cols-3 gap-4 w-full">
          {subjectList.map((subject) => (
            <Card key={subject} title={subject} examType={examType} />
          ))}
        </div>
      ) : (
        <p className="text-amber-800 font-mono text-xl">
          No subjects found for this selection.
        </p>
      )}

      <button
        onClick={() => navigate("/PYPs")}
        className="hover:scale-105 cursor-pointer bg-[#B83D1E] border-2 border-[#B83D1E] font-mono hover:bg-white hover:text-[#B83D1E] rounded-3xl w-64 h-10 text-white"
      >
        Back
      </button>
    </div>
  );
};

export default Subjects;
